opt_in_rules: # some rules are only opt-in
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - todo
  - file_length

disabled_rules: # rule identifiers to exclude from running
  - variable_name
  - attributes
  - trailing_whitespace
  - force_cast
  - type_body_length
  - valid_docs
  - cyclomatic_complexity
  - nesting
  - function_parameter_count
  - large_tuple
  - empty_parentheses_with_trailing_closure
  - line_length
  - notification_center_detachment
  - type_name
  - function_body_length

excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Data
  - Pods
  - R.generated.swift
  - .bundle
